# Generated by Django 6.0 on 2025-12-27 18:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilAcesso',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nivel_acesso', models.CharField(choices=[('EMPRESA', 'Visualização Total (Empresa)'), ('UNIDADE', 'Visualização por Unidade'), ('SETOR', 'Visualização por Setor')], default='SETOR', max_length=20)),
                ('ativo', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(blank=True, help_text='Empresa à qual o usuário tem acesso', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
                ('setores', models.ManyToManyField(blank=True, help_text='Setores aos quais o usuário tem acesso (se nível = SETOR)', to='core.setor')),
                ('unidades', models.ManyToManyField(blank=True, help_text='Unidades às quais o usuário tem acesso (se nível = UNIDADE)', to='core.unidade')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_acesso', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Acesso',
                'verbose_name_plural': 'Perfis de Acesso',
                'db_table': 'perfis_acesso',
            },
        ),
    ]
