# Generated by Django 5.1.15 on 2025-12-30 01:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_perfilacesso_empresas"),
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="perfilacesso",
            name="empresa",
            field=models.ForeignKey(
                blank=True,
                help_text="[DEPRECATED] Use 'empresas' para múltiplas empresas",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="perfis_acesso_legacy",
                to="core.empresa",
            ),
        ),
        migrations.CreateModel(
            name="PasswordResetToken",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "token",
                    models.CharField(
                        db_index=True, max_length=100, unique=True, verbose_name="Token"
                    ),
                ),
                ("expires_at", models.DateTimeField(verbose_name="Expira em")),
                (
                    "is_used",
                    models.BooleanField(default=False, verbose_name="Foi utilizado"),
                ),
                (
                    "used_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Utilizado em"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Endereço IP"
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(blank=True, null=True, verbose_name="User Agent"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="password_reset_tokens",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Token de Redefinição de Senha",
                "verbose_name_plural": "Tokens de Redefinição de Senha",
                "db_table": "password_reset_tokens",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["token", "is_used"], name="password_re_token_82eaa5_idx"
                    ),
                    models.Index(
                        fields=["user", "is_used"],
                        name="password_re_user_id_cd37a3_idx",
                    ),
                ],
            },
        ),
    ]
