# Generated by Django 6.0 on 2025-12-27 18:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=255, unique=True)),
                ('ativa', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'empresas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Unidade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=255)),
                ('ativa', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidades', to='core.empresa')),
            ],
            options={
                'db_table': 'unidades',
                'ordering': ['nome'],
                'unique_together': {('empresa', 'nome')},
            },
        ),
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=255)),
                ('ativo', models.BooleanField(default=True)),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='setores', to='core.unidade')),
            ],
            options={
                'db_table': 'setores',
                'ordering': ['nome'],
                'unique_together': {('unidade', 'nome')},
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('LOGIN', 'Login realizado'), ('LOGOUT', 'Logout realizado'), ('IMPORT_START', 'Importação iniciada'), ('IMPORT_SUCCESS', 'Importação concluída'), ('IMPORT_ERROR', 'Erro na importação'), ('MAGIC_LINK_GENERATED', 'Magic link gerado'), ('MAGIC_LINK_SENT', 'Magic link enviado'), ('MAGIC_LINK_ACCESSED', 'Magic link acessado'), ('MAGIC_LINK_EXPIRED', 'Magic link expirado'), ('QUIZ_STARTED', 'Questionário iniciado'), ('QUIZ_COMPLETED', 'Questionário concluído'), ('QUIZ_ABANDONED', 'Questionário abandonado'), ('DASHBOARD_ACCESSED', 'Dashboard acessado'), ('ANONYMITY_BLOCK', 'Bloqueio por anonimato'), ('CALCULATION_PERFORMED', 'Cálculo realizado')], max_length=50)),
                ('description', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='audit_logs_created_43fcd6_idx'), models.Index(fields=['action'], name='audit_logs_action_31f574_idx'), models.Index(fields=['user'], name='audit_logs_user_id_73c422_idx')],
            },
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=255)),
                ('ativo', models.BooleanField(default=True)),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargos', to='core.setor')),
            ],
            options={
                'db_table': 'cargos',
                'ordering': ['nome'],
                'unique_together': {('setor', 'nome')},
            },
        ),
    ]
