# Generated by Django 6.0 on 2025-12-27 18:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('importacao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dimensao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descricao', models.TextField()),
                ('polaridade', models.CharField(choices=[('POSITIVA', 'Positiva (menor pontuação = maior risco)'), ('NEGATIVA', 'Negativa (maior pontuação = maior risco)')], max_length=10)),
                ('ordem', models.IntegerField(default=0)),
                ('ativa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Dimensão',
                'verbose_name_plural': 'Dimensões',
                'db_table': 'dimensoes',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='MagicLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('ACCESSED', 'Acessado'), ('COMPLETED', 'Concluído'), ('EXPIRED', 'Expirado')], default='PENDING', max_length=20)),
                ('expires_at', models.DateTimeField()),
                ('first_accessed_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('colaborador', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='magic_link', to='importacao.colaborador')),
            ],
            options={
                'db_table': 'magic_links',
            },
        ),
        migrations.CreateModel(
            name='Pergunta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('numero', models.IntegerField(help_text='Número da pergunta no questionário', unique=True)),
                ('texto', models.TextField()),
                ('opcoes_texto', models.CharField(default='(0) nunca; (1) raramente; (2) às vezes; (3) frequentemente; (4) sempre', max_length=255)),
                ('pontuacao_maxima', models.IntegerField(default=4)),
                ('ativa', models.BooleanField(default=True)),
                ('dimensao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perguntas', to='quiz.dimensao')),
            ],
            options={
                'db_table': 'perguntas',
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('respostas', models.JSONField(default=dict)),
                ('score_global', models.FloatField(blank=True, null=True)),
                ('scores_dimensoes', models.JSONField(blank=True, default=dict)),
                ('tempo_total_segundos', models.IntegerField(blank=True, null=True)),
                ('magic_link', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resposta', to='quiz.magiclink')),
            ],
            options={
                'db_table': 'respostas',
            },
        ),
        migrations.AddIndex(
            model_name='magiclink',
            index=models.Index(fields=['token_hash'], name='magic_links_token_h_8d6287_idx'),
        ),
        migrations.AddIndex(
            model_name='magiclink',
            index=models.Index(fields=['status'], name='magic_links_status_a0ea1c_idx'),
        ),
    ]
